### ISSUE TITLE
下载课程视频资源的功能

### ISSUE THREAD

**Issue by HuangZhenyang** [GentleCP/UCASHelper#1]
课程视频资源的链接没有加密，可以考虑加一个下载课程视频的功能
就是不知道有这个需求的人多不多，我随便提的 :)

**Comment by GentleCP** [comment]
视频这个只是临时的吧，等返校了就用不到了，没啥必要弄，而且直接在网络面板就可以打开视频原链接了，自己就可以点击下载，需求也不是很大。
