### ISSUE TITLE
无法评教

### ISSUE THREAD

**Issue by IanSmith123** [GentleCP/UCASHelper#2]
![image](https://user-images.githubusercontent.com/19611084/81564082-c6b9db00-93c9-11ea-9af0-1042f3efbe3e.png)

执行命令后没有评教

**Comment by GentleCP** [comment]
你没有更新呀，git pull一下，1.7.0版本更新了，之前的评教方法不行了

**Comment by IanSmith123** [comment]
更新之后问题修复，感谢。
