### ISSUE TITLE
请问本科生可以用吗？

### ISSUE THREAD

**Issue by HarrisonLiang123** [GentleCP/UCASHelper#3]
在下本科生一枚，想用UCASHelper,在pycharm安装运行之后提示错误

**Comment by GentleCP** [comment]
> 在下本科生一枚，想用UCASHelper,在pycharm安装运行之后提示错误

不知道你报的是什么错误呢？如果可以用[sep系统 ](http://sep.ucas.ac.cn/)登录的话都是可以用的，请确保按照安装指示安装了对应依赖包。

**Comment by GentleCP** [comment]
> 在下本科生一枚，想用UCASHelper,在pycharm安装运行之后提示错误

发现是因为课程网站更换协议导致的出错，已经修复bug并且迭代了版本，请用最新的版本，并按照使用提示再试一次
